# This is a basic workflow to help you get started with Actions

name: license_checker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  license:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Licensed CI
      uses: jonabc/licensed-ci@v1.5.0
      with:
        # Access token to push license updates to GitHub
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: license.yml
